swagger: '2.0'
info:
  description: Bus app API documentation
  version: 1.0.0
  title: Bus App
basePath: /api/v1
tags:
  - name: bus
    description: ''
  - name: bus_stop
    description: ''
  - name: trip
    description: ''
  - name: route
    description: ''
paths:
  /bus:
    post:
      tags:
        - bus
      summary: Add a new bus
      description: ''
      operationId: addBus
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Bus object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Bus'
      responses:
        '200':
          description: Bus created
        '400':
          description: errors in input data
    get:
      tags:
        - bus
      summary: Get list of buses
      description: ''
      operationId: getBuss
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: list of bus
        '400':
          description: errors in input data
  '/bus/{busId}':
    get:
      tags:
        - bus
      summary: Find bus by Id
      description: Returns a single bus
      operationId: getBusById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busId
          in: path
          description: ID of bus to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bus'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus not found
    put:
      tags:
        - bus
      summary: Update bus by Id
      description: Updates a bus
      operationId: updateBusById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busId
          in: path
          description: ID of bus to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bus'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus not found
    delete:
      tags:
        - bus
      summary: Delete bus by Id
      description: Deletes bus object
      operationId: deleteBusById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busId
          in: path
          description: ID of bus to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bus'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus not found
  /bus_stop:
    post:
      tags:
        - bus_stop
      summary: Add a new bus stop
      description: ''
      operationId: addBusStop
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Bus stop object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/BusStop'
      responses:
        '200':
          description: Bus stop created
        '400':
          description: errors in input data
    get:
      tags:
        - bus_stop
      summary: Get list of bus stops
      description: ''
      operationId: getBusStop
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: list of bus stops
        '400':
          description: errors in input data
  '/bus_stop/{busStopId}':
    get:
      tags:
        - bus_stop
      summary: Find bus stop by Id
      description: Returns a single bus
      operationId: getBusStopById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busStopId
          in: path
          description: ID of bus stop to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BusStop'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus stop not found
    put:
      tags:
        - bus_stop
      summary: Update bus stop by Id
      description: Updates a bus stop
      operationId: updateBusStopById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busStopId
          in: path
          description: ID of bus stop to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/BusStop'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus stop not found
    delete:
      tags:
        - bus_stop
      summary: Delete bus stop by Id
      description: Deletes bus stop object
      operationId: deleteBusStopById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: busStopId
          in: path
          description: ID of bus stop to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bus'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bus stop not found
  /trip:
    post:
      tags:
        - trip
      summary: Add a new Trip
      description: ''
      operationId: addTrip
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Trip object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Trip'
      responses:
        '200':
          description: Trip created
        '400':
          description: errors in input data
    get:
      tags:
        - trip
      summary: Get list of trips
      description: ''
      operationId: getTrip
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: list of trips
        '400':
          description: errors in input data
  '/trip/{tripId}':
    get:
      tags:
        - trip
      summary: Find trip by Id
      description: Returns a single trip
      operationId: getTripById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Bus'
        '400':
          description: Invalid ID supplied
        '404':
          description: Trip not found
    put:
      tags:
        - trip
      summary: Update trip by Id
      description: Updates a trip
      operationId: updateTripById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Trip'
        '400':
          description: Invalid ID supplied
        '404':
          description: Trip not found
    delete:
      tags:
        - trip
      summary: Delete trip by Id
      description: Deletes trip object
      operationId: deleteTripById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: tripId
          in: path
          description: ID of trip to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Trip'
        '400':
          description: Invalid ID supplied
        '404':
          description: Trip not found
  /route:
    post:
      tags:
        - route
      summary: Add a new route
      description: ''
      operationId: addRoute
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: Route object that needs to be added
          required: true
          schema:
            $ref: '#/definitions/Route'
      responses:
        '200':
          description: Route created
        '400':
          description: errors in input data
    get:
      tags:
        - route
      summary: Get list of routes
      description: ''
      operationId: getRoutes
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: list of route
        '400':
          description: errors in input data
  '/route/{routeId}':
    get:
      tags:
        - route
      summary: Find route by Id
      description: Returns a single route
      operationId: getRouteById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Route'
        '400':
          description: Invalid ID supplied
        '404':
          description: Route not found
    put:
      tags:
        - route
      summary: Update route by Id
      description: Updates a route
      operationId: updateRouteById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Route'
        '400':
          description: Invalid ID supplied
        '404':
          description: Route not found
    delete:
      tags:
        - route
      summary: Delete route by Id
      description: Deletes route object
      operationId: deleteRouteById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: routeId
          in: path
          description: ID of route to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Route'
        '400':
          description: Invalid ID supplied
        '404':
          description: Route not found
definitions:
  Bus:
    type: object
    properties:
      id:
        type: integer
      bus_reg_no:
        type: string
        maximum: 12
      bus_name:
        type: string
        maximum: 50
  Route:
    type: object
    properties:
      id:
        type: integer
      starts_from:
        type: string
        maximum: 50
      ends_at:
        type: string
        maximum: 50
  Trip:
    type: object
    properties:
      id:
        type: integer
      route:
        $ref: '#/definitions/Route'
      bus:
        $ref: '#/definitions/Bus'
      trip_starting_time:
        type: integer
  BusStop:
    type: object
    properties:
      id:
        type: integer
      part_of_trip:
        $ref: '#/definitions/Trip'
      stop_name:
        type: string
      bus_arrival_time:
        type: integer
